merk_corp_jenkins_monitor:
    resource: "@MerkCorpJenkinsMonitorBundle/Controller/"
    type:     annotation
    prefix:   /

curler:
    resource: "@CurlerBundle/Resources/config/routing.yml"
    prefix:   /