<?php

namespace MerkCorp\JenkinsMonitorBundle\Repository;

/**
 * JenkinsInstanceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class JenkinsInstanceRepository extends \Doctrine\ORM\EntityRepository
{
}
